GET {{host}}/
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.hasOwnProperty("test") && response.body.test === "Test", "Unknown response")
});
%}